name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Make and run tests
      run: make test
    - name: Get coverage report
      run: sudo .github/scripts/get_code_cov.sh
    - name: Upload coverage report to Codecov 
      uses: codecov/codecov-action@v2.0.3
      with:
        flags: unittest
        fail_ci_if_error: true
        verbose: true
