name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Make and run tests
      run: make test COV=1
    - name: Check tests
      run: if grep -q FAIL build/results/test_info.txt; then echo "::error::At least 1 test failed" && exit 1; fi
    - name: Get coverage report
      run: sudo .github/scripts/get_code_cov.sh
    - name: Upload coverage report to Codecov 
      uses: codecov/codecov-action@v2.1.0
      with:
        flags: unittest
        fail_ci_if_error: true
        verbose: true
